# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32b8b77b74347e557f8a8c6052ddcb91d9361c5e3fb999ee9710a853968ffa8d55fc42b80d8d920d22350d8601f36756ae151e9035c8b0c6a1f33ce5ccc9f120

test:
  secret_key_base: f37d5b7db18e23429f153826be485004e7dedc7376b50d99ef8f80a2d339571e29c20a3be8ae8a17be5f9727481ac8976fb2be3f2559953fee6e0478885ac590

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
